### ISSUE TITLE
JDBC Url does not support % character in the password

### ISSUE THREAD

**Issue by christian-sattler** [HuemulSolutions/huemul-bigdatagovernance#111]
**Describe the bug**
When the jdbc connection password has a % (percentage) character, the connection to the model fails

**To Reproduce**
1. Config jdbc password in globalSetting with % caracter

**Error Log**
20/05/20 10:37:32 INFO com.huemulsolutions: establishing connection with control model
Exception in thread "main" java.sql.SQLException: Invalid Oracle URL specified
                at oracle.jdbc.driver.PhysicalConnection.parseUrl(PhysicalConnection.java:1213)
                at oracle.jdbc.driver.PhysicalConnection.readConnectionProperties(PhysicalConnection.java:982)
                at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:646)
                at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:428)
                at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:38)
                at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:691)
                at java.sql.DriverManager.getConnection(DriverManager.java:664)
                at java.sql.DriverManager.getConnection(DriverManager.java:270)
                at com.huemulsolutions.bigdata.control.huemul_JDBCProperties.StartConnection(huemul_JDBCResult.scala:83)
                at com.huemulsolutions.bigdata.common.huemul_BigDataGovernance.<init>(huemul_BigDataGovernance.scala:417)
                at cl.sii.sdi.hdp.obligadostributarios.calculos.process.prc_dc_constantes_declaraciones$.main(prc_dc_constantes_declaraciones.scal\
a:16)

**Comment by huemulDeveloper** [comment]
¿puedes incluir un ejemplo del código en scala para ver como están enviando la password?

**Comment by huemulDeveloper** [comment]
Se agregan dos métodos en la clase huemul_KeyValuePath que permiten asignar un userName y password a la conexión al modelo de control. Con esto se puede elegir entre enviar usuario y password por el connectionString, o usando estos nuevos métodos

A modo de ejemplo, los métodos se usan de la siguiente forma.

```scala
   Global.CONTROL_Setting.append(new huemul_KeyValuePath("production",controlConnString)
     .setUserName(controlUserName)
     .setPassword(controlPassword)
   )
```
